---
- name: Install Nginx in server
  hosts: all
  become: yes

  tasks:
    - name: install epel
      shell: amazon-linux-extras install epel -y|
             yum-config-manager --enable epel

    - name: install nginx
      yum: name=nginx state=present

    - name: service for nginx
      service: name=nginx state=started enabled=yes
 
    - name: copy conf.file nginx
      copy:
        src: /Ansible/nginx.conf
        dest: /etc/nginx/
      notify: Restart Nginx
   

  handlers:
    - name: Restart Nginx
      service: name=nginx state=restarted
